project_id = "mofwljpreecqqxkilywh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-order]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp-and-create-order]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.whatsapp-setup]
verify_jwt = false

[functions.whatsapp-qr-simple]
verify_jwt = false

[functions.whatsapp-direct]
verify_jwt = false

[functions.whatsapp-simple]
verify_jwt = false

[functions.whatsapp-real]
verify_jwt = false

[functions.whatsapp-realtime]
verify_jwt = false

[functions.whatsapp-websocket]
verify_jwt = false

[functions.whatsapp-bridge-proxy]
verify_jwt = false

[functions.vendor-order-automation]
verify_jwt = true

[functions.sync-vendor-prices]
verify_jwt = true

[functions.binance-payment-verify]
verify_jwt = false

[functions.verify-local-wallet-transaction]
verify_jwt = false

[functions.wp-json-api]
verify_jwt = false

[functions.wc-auth-callback-proxy]
verify_jwt = false

[functions.virtual-tryon]
verify_jwt = false

[functions.check-gemini-key]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.generate-product-seo]
verify_jwt = false

[functions.activate-calling-subscription]
verify_jwt = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_autoconfirm = false
enable_phone_confirmations = false
enable_phone_autoconfirm = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_path = "./supabase/templates"

[auth.sms]
enable_signup = false
enable_confirmations = false
template_path = "./supabase/templates"

[edge_runtime]
enabled = true
port = 54329
inspector_port = 8083