import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    console.log('Fetching cached sitemap...')

    // Get the cached sitemap from the database (generated by regenerate_sitemap function)
    const { data: cachedSitemap, error: cacheError } = await supabase
      .from('sitemap_cache')
      .select('xml_content, generated_at')
      .order('generated_at', { ascending: false })
      .limit(1)
      .single()

    if (cacheError || !cachedSitemap) {
      console.log('No cached sitemap found, regenerating...')
      
      // Call the database function to regenerate sitemap
      const { error: regenError } = await supabase.rpc('regenerate_sitemap')
      
      if (regenError) {
        console.error('Error regenerating sitemap:', regenError)
        throw new Error('Failed to regenerate sitemap')
      }

      // Fetch the newly generated sitemap
      const { data: newSitemap, error: newError } = await supabase
        .from('sitemap_cache')
        .select('xml_content')
        .order('generated_at', { ascending: false })
        .limit(1)
        .single()

      if (newError || !newSitemap) {
        throw new Error('Failed to fetch regenerated sitemap')
      }

      console.log('Sitemap regenerated and fetched successfully')
      
      return new Response(newSitemap.xml_content, {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/xml',
        }
      })
    }

    console.log('Cached sitemap found, generated at:', cachedSitemap.generated_at)

    return new Response(cachedSitemap.xml_content, {
      headers: {
        ...corsHeaders,
        'Content-Type': 'application/xml',
      }
    })

  } catch (error) {
    console.error('Error fetching sitemap:', error)
    const message = error instanceof Error ? error.message : 'Unknown error'
    return new Response(
      JSON.stringify({ error: 'Failed to fetch sitemap', details: message }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    )
  }
})
